spring:
  application:
    name: securityTest
  # 데이터베이스 설정
  datasource:
    url: jdbc:postgresql://localhost:5432/test-db
    username: postgres
    password: 0417
    driver-class-name: org.postgresql.Driver
  # JPA 설정
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    show-sql: true
  # Redis 설정
  data:
    redis:
      host: localhost
      port: 6379 # redis 데이터베이스는 기본적으로 6379 포트 사용

# JWT 설정
jwt:
  secret: ksdf98asjkdln9081u9023ndfoiqwernvsdfiu23ndf8923

# 로그 설정
logging:
  level:
    org:
      springframework: info
      zerock: debug

# Swagger 설정
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
    config-url: /api-docs/swagger-config
    url: /api-docs
  default-produces-media-type: application/json
  default-consumes-media-type: application/json

  