# src/main/resources/application-local.yml

server:
  # 혹시 모를 포트 충돌을 피하기 위해 로컬에서는 다른 포트를 사용할 수 있습니다.
  port: 8088

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/test-db
    username: postgres
    password: eg
  data:
    redis:
      host: localhost
      port: 6379

jwt:
  # 로컬 개발용 비밀키는 여기에 직접 작성해도 괜찮습니다.
  secret: "ksdf98asjkdln9081u9023ndfoiqwernvsdfiu23ndf8923"