# src/main/resources/application.yml

spring:
  # IDE 등에서 바로 실행 시 기본적으로 local 프로필이 활성화됩니다.
  profiles:
    active: local
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    show-sql: true
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

# springdoc 등 다른 공통 설정은 여기에 유지합니다.
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html

# 로깅 레벨 설정
logging:
  level:
    org:
      springframework: info
      zerock: debug