version: "3.8"

services:
  db:
    image: postgres:15
    container_name: eg-postgres-db
    # .env 파일의 변수를 사용하도록 변경합니다.
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init-category.sql:/docker-entrypoint-initdb.d/init-category.sql

  redis:
    image: redis:7-alpine
    container_name: eg-redis
    ports:
      - "6379:6379"

  spring-boot-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: eg-spring-app
    ports:
      - "8080:8080"
    # ⭐️⭐️⭐️ 변경된 부분 ⭐️⭐️⭐️
    # .env 파일을 읽어 컨테이너에 환경 변수로 주입합니다.
    # 이렇게 하면 민감한 정보와 환경별 설정을 코드와 분리할 수 있습니다.
    env_file:
      - .env
    depends_on:
      - db
      - redis

volumes:
  pgdata:
