version: "3.8"

services:
  db:
    image: postgres:15
    container_name: eg-postgres-db
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init-category.sql:/docker-entrypoint-initdb.d/init-category.sql

  spring-boot-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: eg-spring-app
    ports:
      - "8080:8080"
    env_file:
      - .env
    depends_on:
      - db
    restart: unless-stopped

volumes:
  pgdata:
