version: "3.8"

services:
  db:
    image: postgres:15
    container_name: eg-postgres-db
    environment:
      POSTGRES_DB: test-db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: eg
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init-category.sql:/docker-entrypoint-initdb.d/init-category.sql

  redis:
    image: redis:7-alpine
    container_name: eg-redis
    ports:
      - "6379:6379"

  spring-boot-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: eg-spring-app
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_HOST: db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: eg
      SPRING_REDIS_HOST: redis
      SPRING_REDIS_PORT: 6379
    depends_on:
      - db
      - redis

volumes:
  pgdata:
